"$schema" = "./theme-schema.json"

bg = "#161616"
fg = "#fff"

[highlights]
attribute = { color = "#c7abe9" }
boolean = { color = "#ff732e", font_weight = 900 }
comment = { color = "#888" }
constant = { color = "#79b8ff" }
"constant.builtin" = { color = "#ff732e", font_weight = 900 }
constructor = { color = "#79b8ff" }
enum = { color = "#b392f1" }
emphasis = { color = "#ff9f5b", font_style = "italic" }
"emphasis.strong" = { color = "#ff9f5b", font_weight = 900 }
function = { color = "#b392f1" }
keyword = { color = "#fa7584" }
label = { color = "#ccc" }
"link.text" = { color = "#ff9f5b" }
"link.uri" = { color = "#ff9f5b" }
link_text = { color = "#ff9f5b" }
link_uri = { color = "#ff9f5b" }
number = { color = "#ff732e" }
operator = { color = "#ccc" }
preproc = { color = "#fa7584" }
property = { color = "#ccc" }
punctuation = { color = "#555" }
string = { color = "#ff9f5b" }
"string.special.symbol" = { color = "#fed75c" }
tag = { color = "#ff9f5b" }
"text.literal" = { color = "#e394dc" }
title = { color = "#ccc" }
type = { color = "#79b8ff" }
variable = { color = "#ccc" }
"variable.special" = { color = "#79b8ff" }
